/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as claimSol from "./Claim.sol";
export type { claimSol };
import type * as commitmentSol from "./Commitment.sol";
export type { commitmentSol };
import type * as pagaSol from "./PAGA.sol";
export type { pagaSol };
import type * as voterSol from "./Voter.sol";
export type { voterSol };
export type { Politician } from "./Politician";
export * as factories from "./factories";
export type { ClaimContract } from "./Claim.sol/ClaimContract";
export { ClaimContract__factory } from "./factories/Claim.sol/ClaimContract__factory";
export type { CommitmentContract } from "./Commitment.sol/CommitmentContract";
export { CommitmentContract__factory } from "./factories/Commitment.sol/CommitmentContract__factory";
export type { PAGAContract } from "./PAGA.sol/PAGAContract";
export { PAGAContract__factory } from "./factories/PAGA.sol/PAGAContract__factory";
export { Politician__factory } from "./factories/Politician__factory";
export type { VoterContract } from "./Voter.sol/VoterContract";
export { VoterContract__factory } from "./factories/Voter.sol/VoterContract__factory";
