/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as claimSol from "./Claim.sol";
export * as commitmentSol from "./Commitment.sol";
export * as pagaSol from "./PAGA.sol";
export * as voterSol from "./Voter.sol";
export { Lock__factory } from "./Lock__factory";
export { Politician__factory } from "./Politician__factory";
export { User__factory } from "./User__factory";
